import { NextResponse } from "next/server";
import { createSupabaseServer } from "@/lib/supabase/server";
import { createSupabaseAdmin } from "@/lib/supabase/admin";
import { notifyRole, writeAudit } from "@/lib/utils/notifications";
import { dispatchOutbound } from "@/lib/integrations/outbound";
import { bookingSchema, customerSchema, validationMessage } from "@/lib/validation/booking";

export async function POST(req: Request) {
  const supabase = await createSupabaseServer();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { data: profile } = await supabase
    .from("app_users").select("id, role, status, name").eq("id", user.id).maybeSingle();
  if (!profile || profile.status !== "APPROVED") {
    return NextResponse.json({ error: "Access pending Director approval." }, { status: 403 });
  }
  if (!["SM","CP","ADMIN","DIRECTOR"].includes(profile.role)) {
    return NextResponse.json({ error: "Role not permitted." }, { status: 403 });
  }

  const body = await req.json().catch(() => null);
  if (!body) return NextResponse.json({ error: "Invalid request body." }, { status: 400 });
  const { customer, customers, booking, initialPayment, previousPayments, attachment } = body ?? {};

  const customerList = Array.isArray(customers) && customers.length ? customers : [customer];
  if (!booking || typeof booking !== "object") {
    return NextResponse.json({ error: "Booking details are required." }, { status: 400 });
  }

  const customerResults = customerList.map((person: unknown) => customerSchema.safeParse(person));
  const invalidCustomer = customerResults.find((result) => !result.success);
  if (invalidCustomer && !invalidCustomer.success) return NextResponse.json({ error: validationMessage(invalidCustomer) }, { status: 400 });
  const totalValue = Number(booking.total_property_value);
  const previous = Number(previousPayments ?? 0);
  const current = Number(initialPayment?.amount ?? 0);
  const bookingResult = bookingSchema.safeParse({
    ...booking,
    previous_payments: previous,
    current_payment: current,
    payment_date: initialPayment?.payment_date ?? new Date().toISOString().slice(0, 10),
    payment_mode: initialPayment?.payment_mode ?? "OTHER",
    reference_no: initialPayment?.reference_no ?? "",
    loan_sanctioned: booking.loan_sanctioned ? "yes" : "no",
  });
  if (!bookingResult.success) return NextResponse.json({ error: validationMessage(bookingResult) }, { status: 400 });

  const admin = createSupabaseAdmin();

  function customerInsert(person: any) {
    return {
      title: person.title?.trim() || null,
      name: person.name.trim(),
      father_spouse_name: person.father_spouse_name?.trim() || null,
      date_of_birth: person.date_of_birth || null,
      address: person.address?.trim() || null,
      city: person.city?.trim() || null,
      state: person.state?.trim() || null,
      country: person.country?.trim() || null,
      pin_code: person.pin_code?.trim() || null,
      phone: person.phone?.trim() || null,
      alternate_phone: person.alternate_phone?.trim() || null,
      email: person.email?.trim() || null,
      alternate_email: person.alternate_email?.trim() || null,
      pan_number: person.pan_number?.trim().toUpperCase() || null,
      aadhaar_number: person.aadhaar_number?.trim() || null,
      occupation: person.occupation?.trim() || null,
      organization: person.organization?.trim() || null,
      designation: person.designation?.trim() || null,
      created_by: profile.id,
    };
  }

  // 1. Insert customer
  const { data: cust, error: custErr } = await admin
    .from("customers")
    .insert(customerInsert(customerList[0]))
    .select("id")
    .single();
  if (custErr) return NextResponse.json({ error: custErr.message }, { status: 500 });

  // 2. Insert booking (booking_id auto-generated by DB default)
  const { data: bk, error: bkErr } = await admin
    .from("bookings")
    .insert({
      customer_id: cust.id,
      project_name: booking.project_name,
      unit_number: booking.unit_number,
      property_details: booking.property_details ?? null,
      total_property_value: totalValue,
      notes: booking.notes ?? null,
      bank_name: booking.bank_name ?? null,
      bank_account_holder: booking.bank_account_holder ?? null,
      bank_account_number: booking.bank_account_number ?? null,
      bank_ifsc: booking.bank_ifsc ?? null,
      bank_branch: booking.bank_branch ?? null,
      loan_sanctioned: Boolean(booking.loan_sanctioned),
      loan_amount: booking.loan_amount ?? null,
      sales_representative: booking.sales_representative ?? null,
      team_manager: booking.team_manager ?? null,
      booking_place: booking.booking_place ?? null,
      booking_date: booking.booking_date ?? null,
      block: booking.block ?? null,
      facing: booking.facing ?? null,
      saleable_area: booking.saleable_area ?? null,
      carpet_area: booking.carpet_area ?? null,
      external_walls_area: booking.external_walls_area ?? null,
      balcony_utility_area: booking.balcony_utility_area ?? null,
      common_area: booking.common_area ?? null,
      base_price: booking.base_price ?? null,
      floor_rise_charges: booking.floor_rise_charges ?? null,
      east_facing_charges: booking.east_facing_charges ?? null,
      premium_view_charges: booking.premium_view_charges ?? null,
      amenities_charges: booking.amenities_charges ?? null,
      car_parking_charges: booking.car_parking_charges ?? null,
      legal_documentation_charges: booking.legal_documentation_charges ?? null,
      sale_consideration_per_sqft: booking.sale_consideration_per_sqft ?? null,
      source_of_booking: booking.source_of_booking ?? null,
      referral_customer_name: booking.referral_customer_name ?? null,
      referral_project_name: booking.referral_project_name ?? null,
      cp_agent_name: booking.cp_agent_name ?? null,
      cp_rera_id: booking.cp_rera_id ?? null,
      payment_source: booking.payment_source ?? null,
      purchase_purpose: booking.purchase_purpose ?? null,
      status: "SUBMITTED",
      created_by: profile.id,
      creator_role: profile.role,
      submitted_at: new Date().toISOString()
    })
    .select("id, booking_id")
    .single();
  if (bkErr) return NextResponse.json({ error: bkErr.message }, { status: 500 });

  // Link every buyer/co-buyer. The first person remains the legacy primary
  // customer on bookings.customer_id.
  const customerRows: { booking_id: string; customer_id: string; is_primary: boolean }[] = [];
  for (const [index, person] of customerList.entries()) {
    if (!person?.name) continue;
    let customerId = index === 0 ? cust.id : null;
    if (!customerId) {
      const { data: extra, error: extraErr } = await admin.from("customers").insert(customerInsert(person)).select("id").single();
      if (extraErr) return NextResponse.json({ error: extraErr.message }, { status: 500 });
      customerId = extra.id;
    }
    customerRows.push({ booking_id: bk.id, customer_id: customerId, is_primary: index === 0 });
  }
  const { error: linkErr } = await admin.from("booking_customers").insert(customerRows);
  if (linkErr) return NextResponse.json({ error: linkErr.message }, { status: 500 });

  // 3. Seed previous payments as one aggregate APPROVED record if > 0
  if (previous > 0) {
    await admin.from("payments").insert({
      booking_id: bk.id,
      amount: previous,
      payment_date: new Date().toISOString().slice(0, 10),
      payment_mode: "OTHER",
      reference_no: "OPENING_BALANCE",
      status: "APPROVED",
      submitted_by: profile.id,
      reviewed_by: profile.id,
      reviewed_at: new Date().toISOString(),
      notes: "Migrated / previous payments"
    });
  }

  // 4. Initial payment goes in as PENDING for Accountant review
  if (current > 0) {
    await admin.from("payments").insert({
      booking_id: bk.id,
      amount: current,
      payment_date: initialPayment.payment_date,
      payment_mode: initialPayment.payment_mode,
      reference_no: initialPayment.reference_no,
      status: "PENDING",
      submitted_by: profile.id
    });
  }

  // 4b. Link the uploaded document. The file is already in Storage (the
  //     browser uploads on select); this records what it belongs to.
  if (attachment?.storagePath) {
    const { error: attErr } = await admin.from("attachments").insert({
      entity_type: "booking",
      entity_id: bk.id,
      storage_path: attachment.storagePath,
      file_name: attachment.name ?? "document",
      file_size: Number(attachment.size ?? 0) || 1,
      mime_type: attachment.type ?? "application/octet-stream",
      label: "Booking agreement / payment proof",
      uploaded_by: profile.id
    });
    // A failed attachment link must not fail the booking — the booking is the
    // record of value, and the orphaned object is recoverable.
    if (attErr) console.error("[bookings] attachment link failed", attErr.message);
  }

  // 5. Notify accountants
  await notifyRole("ACCOUNTANT", {
    category: "BOOKING",
    title: "New booking submitted",
    message: `${profile.name} submitted booking ${bk.booking_id} for verification.`,
    entityType: "booking",
    entityId: bk.id,
    priority: "HIGH"
  });

  // 6. Audit
  await writeAudit({
    actorUserId: profile.id,
    actorRole: profile.role,
    action: "BOOKING_CREATE",
    entityType: "booking",
    entityId: bk.id,
    newData: { booking_id: bk.booking_id, project_name: booking.project_name, unit_number: booking.unit_number, total_property_value: totalValue }
  });

  // 7. Outbound bridge (WhatsApp + email to the internal ops list).
  //    dispatchOutbound never throws — a failed alert must not turn a
  //    successfully-created booking into a 500.
  await dispatchOutbound({
    key: "BOOKING_SUBMITTED",
    entityId: bk.id,
    data: {
      bookingRef: bk.booking_id,
      bookingUuid: bk.id,
      submitterName: profile.name,
      customerName: customerList[0].name,
      customerEmail: customerList[0].email ?? null,
      project: booking.project_name,
      unit: booking.unit_number,
      totalValue
    }
  });

  return NextResponse.json({ id: bk.id, booking_id: bk.booking_id });
}
