import { NextResponse } from "next/server";
import { createSupabaseServer } from "@/lib/supabase/server";
import { createSupabaseAdmin } from "@/lib/supabase/admin";
import { notifyRole, writeAudit } from "@/lib/utils/notifications";
import { dispatchOutbound } from "@/lib/integrations/outbound";

export async function POST(req: Request) {
  const supabase = createSupabaseServer();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { data: profile } = await supabase
    .from("app_users").select("id, role, status, name").eq("id", user.id).maybeSingle();
  if (!profile || profile.status !== "APPROVED") {
    return NextResponse.json({ error: "Access pending Director approval." }, { status: 403 });
  }
  if (!["SM","CP","ADMIN","DIRECTOR"].includes(profile.role)) {
    return NextResponse.json({ error: "Role not permitted." }, { status: 403 });
  }

  const body = await req.json();
  const { customer, booking, initialPayment, previousPayments, attachment } = body ?? {};

  if (!customer?.name || !booking?.project_name || !booking?.unit_number || !booking?.total_property_value) {
    return NextResponse.json({ error: "Missing required fields." }, { status: 400 });
  }
  const totalValue = Number(booking.total_property_value);
  const previous = Number(previousPayments ?? 0);
  const current = Number(initialPayment?.amount ?? 0);
  if (previous + current > totalValue) {
    return NextResponse.json({ error: "Payments exceed total property value." }, { status: 400 });
  }

  const admin = createSupabaseAdmin();

  // 1. Insert customer
  const { data: cust, error: custErr } = await admin
    .from("customers")
    .insert({
      name: customer.name,
      phone: customer.phone ?? null,
      email: customer.email ?? null,
      created_by: profile.id
    })
    .select("id")
    .single();
  if (custErr) return NextResponse.json({ error: custErr.message }, { status: 500 });

  // 2. Insert booking (booking_id auto-generated by DB default)
  const { data: bk, error: bkErr } = await admin
    .from("bookings")
    .insert({
      customer_id: cust.id,
      project_name: booking.project_name,
      unit_number: booking.unit_number,
      property_details: booking.property_details ?? null,
      total_property_value: totalValue,
      notes: booking.notes ?? null,
      bank_name: booking.bank_name ?? null,
      bank_account_holder: booking.bank_account_holder ?? null,
      bank_account_number: booking.bank_account_number ?? null,
      bank_ifsc: booking.bank_ifsc ?? null,
      bank_branch: booking.bank_branch ?? null,
      loan_sanctioned: Boolean(booking.loan_sanctioned),
      loan_amount: booking.loan_amount ?? null,
      status: "SUBMITTED",
      created_by: profile.id,
      creator_role: profile.role,
      submitted_at: new Date().toISOString()
    })
    .select("id, booking_id")
    .single();
  if (bkErr) return NextResponse.json({ error: bkErr.message }, { status: 500 });

  // 3. Seed previous payments as one aggregate APPROVED record if > 0
  if (previous > 0) {
    await admin.from("payments").insert({
      booking_id: bk.id,
      amount: previous,
      payment_date: new Date().toISOString().slice(0, 10),
      payment_mode: "OTHER",
      reference_no: "OPENING_BALANCE",
      status: "APPROVED",
      submitted_by: profile.id,
      reviewed_by: profile.id,
      reviewed_at: new Date().toISOString(),
      notes: "Migrated / previous payments"
    });
  }

  // 4. Initial payment goes in as PENDING for Accountant review
  if (current > 0) {
    await admin.from("payments").insert({
      booking_id: bk.id,
      amount: current,
      payment_date: initialPayment.payment_date,
      payment_mode: initialPayment.payment_mode,
      reference_no: initialPayment.reference_no,
      status: "PENDING",
      submitted_by: profile.id
    });
  }

  // 4b. Link the uploaded document. The file is already in Storage (the
  //     browser uploads on select); this records what it belongs to.
  if (attachment?.storagePath) {
    const { error: attErr } = await admin.from("attachments").insert({
      entity_type: "booking",
      entity_id: bk.id,
      storage_path: attachment.storagePath,
      file_name: attachment.name ?? "document",
      file_size: Number(attachment.size ?? 0) || 1,
      mime_type: attachment.type ?? "application/octet-stream",
      label: "Booking agreement / payment proof",
      uploaded_by: profile.id
    });
    // A failed attachment link must not fail the booking — the booking is the
    // record of value, and the orphaned object is recoverable.
    if (attErr) console.error("[bookings] attachment link failed", attErr.message);
  }

  // 5. Notify accountants
  await notifyRole("ACCOUNTANT", {
    category: "BOOKING",
    title: "New booking submitted",
    message: `${profile.name} submitted booking ${bk.booking_id} for verification.`,
    entityType: "booking",
    entityId: bk.id,
    priority: "HIGH"
  });

  // 6. Audit
  await writeAudit({
    actorUserId: profile.id,
    actorRole: profile.role,
    action: "BOOKING_CREATE",
    entityType: "booking",
    entityId: bk.id,
    newData: { booking_id: bk.booking_id, project_name: booking.project_name, unit_number: booking.unit_number, total_property_value: totalValue }
  });

  // 7. Outbound bridge (WhatsApp + email to the internal ops list).
  //    dispatchOutbound never throws — a failed alert must not turn a
  //    successfully-created booking into a 500.
  await dispatchOutbound({
    key: "BOOKING_SUBMITTED",
    entityId: bk.id,
    data: {
      bookingRef: bk.booking_id,
      bookingUuid: bk.id,
      submitterName: profile.name,
      customerName: customer.name,
      customerEmail: customer.email ?? null,
      project: booking.project_name,
      unit: booking.unit_number,
      totalValue
    }
  });

  return NextResponse.json({ id: bk.id, booking_id: bk.booking_id });
}
